version: '3.8'

services:
  dm8:
    container_name: crtadgai-dm8
    image: dm8:dm8_20250206_rev257733_x86_rh6_64
    restart: always
    environment:
      - INSTANCE_NAME=CrtadgAiDaMeng
      - SYSDBA_PWD=CrtadgAi@123
    ports:
      - 15236:5236

  redis:
    container_name: crtadgai-redis
    image: redis:latest
    restart: always
    ports:
      - 16379:6379