version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=dedsi@root123
      - MYSQL_USER=dedsi
      - MYSQL_PASS=dedsi@123
    ports:
      - '13306:3306'

  redis:
    container_name: crtadgai-redis
    image: redis:latest
    restart: always
    ports:
      - 16379:6379