using Microsoft.EntityFrameworkCore;

namespace DedsiAuthorization.Openiddict.EntityFrameworkCore;

public class CrtadgAiAuthorizationOpeniddictDbContext(DbContextOptions<CrtadgAiAuthorizationOpeniddictDbContext> options): DbContext(options);